---

 - name: BREW BASE SW CONFIG FROM BASE & J2 TEMPLATE
   hosts: localhost
   gather_facts: no
   connection: local
   vars_files:
    - "../templates/sw-vars.yml"
    - "../templates/sites/siteA.yml"

   tasks:
   
    - name: INJECT TEMPLATE
      template:
       src: sw-temp.j2
       dest: "{{item.value.hostname}}.cfg"
      with_dict: "{{switches}}"

    - name: APPEND BASE
      shell: "cat ../templates/sw-base.cfg >> {{item.value.hostname}}.cfg"
      with_dict: "{{switches}}" 

