version: '3'

services:
 ansible:
  build: ./
  container_name: ansible
  hostname: ansible
  volumes:
   - ./config_changes:/usr/ansible/config_changes
   - ./config_templates:/usr/ansible/config_templates
   - ./server_deployment:/usr/ansible/server_deployment
  ports:
   - "8080:80"
   - "2222:22"
  tty: true
  stdin_open: true
